apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todoapp-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: todoapp
  namespaceSelector:
    matchNames:
      - todoapp
  endpoints:
    - port: http
      interval: 15s
      path: /api/metrics
