apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-final
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data-todoapp"
