apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
  namespace: todoapp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual   # <- обов’язково додати
  resources:
    requests:
      storage: 1Gi
