apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
  namespace: todoapp
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
